[0, 1, 2, 3, 4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31, 32, 33, 34, 40, 41, 42, 43, 44, 50, 51, 52, 53, 54, 60, 61, 62, 63, 64, 70, 71, 72, 73, 74, 80, 81, 82, 83, 84, 90, 91, 92, 93, 94, 100, 101, 102, 103, 104, 110, 111, 112, 113, 114, 120, 121, 122, 123, 124, 130, 131, 132, 133, 134, 140, 141, 142, 143, 144, 150, 151, 152, 153, 154, 160, 161, 162, 163, 164, 170, 171, 172, 173, 174, 180, 181, 182, 183, 184, 190, 191, 192, 193, 194, 200, 201, 202, 203, 204, 210, 211, 212, 213, 214, 220, 221, 222, 223, 224, 230, 231, 232, 233, 234, 240, 241, 242, 243, 244, 250, 251, 252, 253, 254, 260, 261, 262, 263, 264, 270, 271, 272, 273, 274, 280, 281, 282, 283, 284, 290, 291, 292, 293, 294, 300, 301, 302, 303, 304, 310, 311, 312, 313, 314, 320, 321, 322, 323, 324, 330, 331, 332, 333, 334, 340, 341, 342, 343, 344, 350, 351, 352, 353, 354, 360, 361, 362, 363, 364, 370, 371, 372, 373, 374, 380, 381, 382, 383, 384, 390, 391, 392, 393, 394]
  0%|          | 0/200 [00:00<?, ?it/s]  0%|          | 0/200 [02:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/http/client.py", line 1368, in getresponse
    response.begin()
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/http/client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/http/client.py", line 278, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/http/client.py", line 1368, in getresponse
    response.begin()
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/http/client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/http/client.py", line 278, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjtuzky/SimCourt/AgentCourt/baselines/AgentsCourt/AgentsCourt/judge_case_refine.py", line 151, in <module>
    previous_case = yilvkezhi_retriever(case_test["prosecution_statement_sub"])
  File "/home/bjtuzky/SimCourt/AgentCourt/baselines/AgentsCourt/AgentsCourt/judge_case_refine.py", line 51, in yilvkezhi_retriever
    response = requests.request("POST", url, headers=headers, data=payload)
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/bjtuzky/.conda/envs/rag/lib/python3.10/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
